/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 7b6bfe8dd594e3240bd4dad6a1b4a533)
interface __BaseEnv_Env {
	AI: Ai;
	AI_PROVIDER: "workers-ai";
	WORKERS_AI_ACTOR_MODEL: "@cf/nvidia/nemotron-3-120b-a12b";
	WORKERS_AI_EVALUATOR_MODEL: "@cf/nvidia/nemotron-3-120b-a12b";
	ENCOUNTER_SESSION: DurableObjectNamespace /* EncounterSession */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_PROVIDER" | "WORKERS_AI_ACTOR_MODEL" | "WORKERS_AI_EVALUATOR_MODEL">> {}
}
