import type { Character } from '../types';

/**
 * Fictional authoring defaults. Follower counts, names, and accounts are
 * invented for the game and describe no real person.
 */
export const CHARACTERS: Record<string, Character> = {
	mara: {
		id: 'mara',
		name: 'Mara',
		age: 29,
		role: 'principal',
		statusCue: '8.4K followers, well-dressed regular',
		followers: 8400,
		appearance: {
			hair: 'shoulder-length, loose waves',
			hairColor: '#2a1b14',
			skin: '#d9a98a',
			outfit: 'dark teal silk blouse, black trousers',
			outfitColor: '#134e5e',
			accentColor: '#c9a35c',
		},
		personality:
			'Dry humor, playful skepticism. Attracted to composure and wit. Notices defensiveness fast and names it lightly rather than cruelly.',
		voice: 'Short sentences. Understatement. Asks one pointed question at a time. Laughs with a small exhale rather than a big reaction.',
		interests: ['architecture', 'bad reality TV she claims to hate-watch', 'long runs along the waterfront', 'cheap wine, expensive coffee'],
		humor: 'deadpan, enjoys someone who can take a joke and return one without escalating',
		friends: ['Priya (arrives later, protective)', 'the bartender, Theo, who she has known for years'],
		reasonHere: 'Decompressing after closing a project; told herself she would leave by eleven.',
		mood: 'relaxed, mildly amused by the room, willing to talk if the talk is good',
		likesTopics: ['cities and buildings', 'guilty pleasures', 'what people are actually like at work', 'a specific plan rather than a vague one'],
		turnOffs: ['being told what she is thinking', 'performed confidence that needs applause', 'someone who cannot admit an awkward moment', 'lines that could be said to anyone'],
		traits: {
			boldness: 1,
			wit: 2,
			warmth: 1,
			sincerity: 1,
			recognizesRoutines: true,
			enjoysPerformance: false,
			noticesDefensiveness: true,
			dislikesSpotlight: false,
			initiates: false,
		},
		entryNode: 'mara.approach',
		rejectionNodes: ['mara.reject_blunt', 'mara.reject_friendly', 'mara.reject_videos'],
		facts: [
			'She designs interiors for restaurants and hates when people call it decorating.',
			'She has run two half marathons and lied about training for both.',
			'She is here because her project wrapped today and she did not want to go home yet.',
			'She thinks the lounge lighting is the best thing about it and the drinks are the worst.',
		],
		difficultyNote: 'The starter encounter. A reachable positive path exists on every difficulty.',
		actorNotes:
			'Mara rewards a person who listens and answers the actual question. She enjoys a tease when it is specific to her; generic teasing bores her. When the player gets defensive, she goes quieter and more precise. She never explains the rules of the game or comments on scoring.',
	},
	sienna: {
		id: 'sienna',
		name: 'Sienna',
		age: 28,
		role: 'principal',
		statusCue: '84.2K followers, fashion micro-influencer',
		followers: 84200,
		appearance: {
			hair: 'long, straight, center part',
			hairColor: '#b98a5a',
			skin: '#f0cdb4',
			outfit: 'cream satin slip dress, thin gold chain',
			outfitColor: '#e9dcc9',
			accentColor: '#d4af37',
		},
		personality:
			'Selective, socially fluent, comfortable being looked at. Spots stock routines within a sentence and says so. Enjoys bold flirting when it fits the moment and is actually about her.',
		voice: 'Quick, bright, slightly teasing. Comfortable with silence because she knows someone will fill it. Says "okay" as a full sentence.',
		interests: ['vintage designers', 'hotel bars in cities she has not been to', 'a private group chat that runs her life', 'anyone who can hold their own with her friends'],
		humor: 'fast, pointed, likes being surprised, hates being handled',
		friends: ['Brooke (sharp, image-conscious, will interrupt)', 'Dani (kinder, films everything)'],
		reasonHere: 'Content dinner ended early; she is deciding whether the night is over.',
		mood: 'entertained but bored, looking for something that is not a pitch',
		likesTopics: ['what people actually do all day', 'honest opinions about her industry', 'travel that was not for work', 'someone who can talk to her friends without performing'],
		turnOffs: ['being asked about her follower count', 'openers she has heard before', 'a man who competes with her friends for her attention', 'anyone who gets smaller when Brooke shows up'],
		traits: {
			boldness: 2,
			wit: 2,
			warmth: 1,
			sincerity: 1,
			recognizesRoutines: true,
			enjoysPerformance: true,
			noticesDefensiveness: true,
			dislikesSpotlight: false,
			initiates: true,
		},
		entryNode: 'sienna.approach',
		rejectionNodes: ['sienna.reject_dare', 'sienna.reject_normal', 'sienna.reject_friends'],
		facts: [
			'She started posting outfits to pay for a semester abroad and never went.',
			'She turns her phone face down when she decides someone is interesting.',
			'Brooke once talked her out of a relationship in one car ride and she still resents it.',
			'She is from a small town outside Calgary and hides it well.',
		],
		difficultyNote: 'The optional final boss of this lounge. Her friends, her phone, and her pattern recognition make her the most demanding path.',
		actorNotes:
			'Sienna is not cruel; she is efficient. If she recognizes a line she names it and watches what the player does next. Boldness that is specific to her works. Boldness that is a script does not. She warms to someone who treats Brooke as a person instead of an obstacle. She may initiate: comment on the player before he speaks, or hand him a small test.',
	},
	camille: {
		id: 'camille',
		name: 'Camille',
		age: 33,
		role: 'principal',
		statusCue: 'Private account, 611 followers. Everyone knows her.',
		followers: 611,
		appearance: {
			hair: 'short, sleek bob',
			hairColor: '#0e0a08',
			skin: '#8a5a3c',
			outfit: 'black tailored jumpsuit, silver cuff',
			outfitColor: '#171717',
			accentColor: '#b8bcc4',
		},
		personality:
			'High local social influence, reads group dynamics instantly, handles posturing with polite precision. Generous to people who are genuinely curious. Bored by status games she could win in her sleep.',
		voice: 'Measured, warm, precise. Uses people\'s names. Asks follow-up questions that show she was listening. Rarely raises her voice; lowers it instead.',
		interests: ['running a members club two blocks away', 'who is quietly talented in the room', 'old jazz records', 'a garden she does not have time for'],
		humor: 'observational, dry, enjoys someone who notices the same absurdity she does',
		friends: ['Theo the bartender (former employee)', 'half the room, at a distance'],
		reasonHere: 'Checking on a friend\'s new bar program, staying out of habit.',
		mood: 'attentive, evaluating, open to a real conversation',
		likesTopics: ['what makes a room work', 'people\'s actual craft', 'music you can name a year for', 'plans that respect her time'],
		turnOffs: ['being treated as a networking opportunity', 'attempts to impress her with the guest list', 'competing with other men in front of her', 'interrupting her question to answer a different one'],
		traits: {
			boldness: 1,
			wit: 1,
			warmth: 2,
			sincerity: 2,
			recognizesRoutines: true,
			enjoysPerformance: false,
			noticesDefensiveness: true,
			dislikesSpotlight: false,
			initiates: true,
		},
		entryNode: 'camille.approach',
		rejectionNodes: ['camille.reject_polite', 'camille.reject_network', 'camille.reject_time'],
		facts: [
			'She opened her club with money from selling a cafe she ran at twenty-six.',
			'She keeps a list of every person who has ever asked her for a favor before asking her name.',
			'She learned to read rooms working the door for three years.',
			'She wants to leave the city for one year and is afraid it would become permanent.',
		],
		difficultyNote: 'Difficulty comes from social context: she will notice how you treat everyone else.',
		actorNotes:
			'Camille responds to sincerity and curiosity; she gives posturing a polite, precise answer that ends the topic. She notices the bartender, the friends, and the rival, and judges the player on how he treats them. She sometimes initiates by asking a direct question. She never rewards name-dropping.',
	},
	elise: {
		id: 'elise',
		name: 'Elise',
		age: 27,
		role: 'principal',
		statusCue: '203 followers. Striking, low visibility.',
		followers: 203,
		appearance: {
			hair: 'long, dark, tucked behind one ear',
			hairColor: '#1a1210',
			skin: '#e6c3a5',
			outfit: 'oversized charcoal knit, silver rings',
			outfitColor: '#3a3d45',
			accentColor: '#9fb3c8',
		},
		personality:
			'Initially reserved, funny once she trusts the room. Responds to attentive sincerity and quiet humor. Dislikes being made to perform in front of strangers and will shut down if pushed into a spotlight.',
		voice: 'Quiet, careful, unexpectedly sharp. Long pauses. Answers questions honestly and briefly, then expands if the listener seems to care.',
		interests: ['illustrating children\'s books under a different name', 'film photography', 'the strange history of ordinary objects', 'silence, genuinely'],
		humor: 'quiet, observational, surprises people who assumed she was shy',
		friends: ['Noor (dragged her here, dancing somewhere)'],
		reasonHere: 'Noor made her come. She is one drink in and considering leaving.',
		mood: 'wary, then curious if the conversation is gentle and specific',
		likesTopics: ['something small she noticed in the room', 'work people do when nobody is watching', 'a question she has never been asked', 'leaving early without drama'],
		turnOffs: ['being teased in front of other people', 'loud performances', 'questions that feel like an interview', 'pressure to stay or drink more'],
		traits: {
			boldness: 0,
			wit: 1,
			warmth: 2,
			sincerity: 2,
			recognizesRoutines: false,
			enjoysPerformance: false,
			noticesDefensiveness: false,
			dislikesSpotlight: true,
			initiates: false,
		},
		entryNode: 'elise.approach',
		rejectionNodes: ['elise.reject_quiet', 'elise.reject_leave', 'elise.reject_spotlight'],
		facts: [
			'Her illustrations are in a book that is in the window of the shop across the street.',
			'She shoots one roll of film per month and has never posted a frame.',
			'She was going to leave ten minutes before the player walked over.',
			'She likes this lounge only because the bar stools face the window.',
		],
		difficultyNote: 'Bold play tends to backfire. Quiet, specific attention opens her.',
		actorNotes:
			'Elise answers briefly at first and gives more when the player notices something specific and does not make a show of it. Teasing works only if it is gentle and private. If the player pulls other people into the conversation to make her perform, she withdraws. She is not cold; she is careful.',
	},
	theo: {
		id: 'theo',
		name: 'Theo',
		age: 41,
		role: 'bartender',
		statusCue: 'Bartender. Remembers everything.',
		followers: 0,
		appearance: {
			hair: 'close-cropped, greying',
			hairColor: '#4a4540',
			skin: '#c58c66',
			outfit: 'white shirt, sleeves rolled, black apron',
			outfitColor: '#f2f0ea',
			accentColor: '#222',
		},
		personality: 'Dry, kind, tired in a way he enjoys. Has a job to do and a memory of the whole evening.',
		voice: 'Two sentences max. Delivers a joke and walks away to make a drink.',
		interests: ['the closing shift playlist', 'people who tip in cash', 'anyone who orders something he can be proud of'],
		humor: 'deadpan commentary, never at the customer\'s expense in front of the woman',
		friends: ['Mara', 'Camille'],
		reasonHere: 'Working.',
		mood: 'steady',
		likesTopics: ['drinks', 'the room'],
		turnOffs: ['being used as a prop'],
		traits: {
			boldness: 1,
			wit: 2,
			warmth: 1,
			sincerity: 2,
			recognizesRoutines: true,
			enjoysPerformance: false,
			noticesDefensiveness: false,
			dislikesSpotlight: false,
			initiates: true,
		},
		entryNode: '',
		rejectionNodes: [],
		facts: ['He used to work for Camille.', 'He has watched Mara turn down eleven men this year and liked one of them.'],
		difficultyNote: '',
		actorNotes: 'Theo comments on the evening sparingly. He remembers what the player ordered and what happened earlier.',
	},
	brooke: {
		id: 'brooke',
		name: 'Brooke',
		age: 29,
		role: 'friend',
		statusCue: 'Sienna\'s friend. Image-conscious.',
		followers: 31000,
		appearance: {
			hair: 'high ponytail',
			hairColor: '#3b2a1a',
			skin: '#f1d2bd',
			outfit: 'black blazer dress',
			outfitColor: '#121212',
			accentColor: '#ff4d6d',
		},
		personality: 'Sharp, protective, decides fast. Interrupts when she thinks Sienna is wasting time. Can be won over by someone who does not compete with her.',
		voice: 'Fast, clipped, one eyebrow up.',
		interests: ['leaving on time', 'the next place'],
		humor: 'cutting',
		friends: ['Sienna', 'Dani'],
		reasonHere: 'Managing the night.',
		mood: 'impatient',
		likesTopics: ['logistics'],
		turnOffs: ['being ignored', 'being flattered'],
		traits: {
			boldness: 2,
			wit: 1,
			warmth: 0,
			sincerity: 1,
			recognizesRoutines: true,
			enjoysPerformance: false,
			noticesDefensiveness: true,
			dislikesSpotlight: false,
			initiates: true,
		},
		entryNode: '',
		rejectionNodes: [],
		facts: [],
		difficultyNote: '',
		actorNotes: 'Brooke interrupts with a practical demand and judges the player on whether he includes her or bristles.',
	},
	dev: {
		id: 'dev',
		name: 'Dev',
		age: 34,
		role: 'rival',
		statusCue: 'Tall. Knows the owner. Possibly looking for the bathroom.',
		followers: 2100,
		appearance: {
			hair: 'swept back',
			hairColor: '#221a14',
			skin: '#b87a52',
			outfit: 'unbuttoned navy overshirt, statement watch',
			outfitColor: '#1d2a44',
			accentColor: '#cfa96a',
		},
		personality: 'Friendly, loud, oblivious. Sometimes competitive, often just asking a practical question. The coach calls him an AMOG; he calls himself Dev.',
		voice: 'Big, warm, interrupts himself.',
		interests: ['the owner', 'his watch', 'where the bathroom is'],
		humor: 'broad',
		friends: ['everyone, allegedly'],
		reasonHere: 'A friend\'s birthday somewhere on this floor.',
		mood: 'cheerful',
		likesTopics: ['anything'],
		turnOffs: ['being treated as a threat'],
		traits: {
			boldness: 2,
			wit: 1,
			warmth: 2,
			sincerity: 1,
			recognizesRoutines: false,
			enjoysPerformance: true,
			noticesDefensiveness: false,
			dislikesSpotlight: false,
			initiates: true,
		},
		entryNode: '',
		rejectionNodes: [],
		facts: [],
		difficultyNote: '',
		actorNotes: 'Dev is not an enemy. He interrupts with something ordinary and reacts to how the player handles it.',
	},
};

export const PRINCIPALS = ['mara', 'sienna', 'camille', 'elise'] as const;

export function getCharacter(id: string): Character {
	const character = CHARACTERS[id];
	if (!character) {
		throw new Error(`Unknown character: ${id}`);
	}
	return character;
}
