import type { RoutineDefinition } from '../types';

/**
 * Original routines written for the game. Names of historical community
 * routines are documented in the codex, not reproduced here.
 */
export const ROUTINES: Record<string, RoutineDefinition> = {
	observation_opener: {
		id: 'observation_opener',
		name: 'Observation Opener',
		category: 'opener',
		description: 'Open with something specific you actually noticed about her, the drink, or the room, then a light question.',
		beats: ['names one concrete, specific detail present in the scene', 'stays light', 'ends with an easy question or invitation to respond'],
		paraphrases: [
			'That is the only drink on this bar that looks like it was made on purpose. What is it?',
			'You have been watching the door for ten minutes. Waiting or avoiding?',
		],
		suitableKinds: ['conversation'],
		personaRequires: [],
		personaResists: [],
		minStage: 1,
		maxStage: 2,
		effect: { momentum: 4, interest: 2, comfort: 2, trust: 0 },
		backfire: 'A generic observation that could be said to anyone reads as a line.',
		unlockedByDefault: true,
		unlockMastery: 0,
	},
	agree_amplify: {
		id: 'agree_amplify',
		name: 'Agree and Amplify',
		category: 'agree_amplify',
		description: 'When she teases you, accept the premise and exaggerate it until it is absurd. Never defend.',
		beats: ['accepts the teasing premise without defending', 'exaggerates it past plausibility', 'keeps the tone warm'],
		paraphrases: [
			'Guilty. I have a whole binder of openers, this one was page four.',
			'Oh, it is much worse than that. My friends bet against me.',
		],
		suitableKinds: ['tease', 'consistency'],
		personaRequires: [],
		personaResists: [],
		minStage: 2,
		maxStage: 6,
		effect: { momentum: 5, interest: 3, comfort: 1, trust: 0 },
		backfire: 'Amplifying a sincere concern instead of a tease reads as not listening.',
		unlockedByDefault: true,
		unlockMastery: 0,
	},
	playful_reframe: {
		id: 'playful_reframe',
		name: 'Playful Reframe',
		category: 'reframe',
		description: 'Take the frame she just offered and turn it into a shared joke that includes her.',
		beats: ['acknowledges what she said', 'flips the interpretation playfully', 'includes her in the joke rather than targeting her'],
		paraphrases: [
			'So this is an interview. Fine. My weakness is I care too much about which bar stool I sit on.',
			'Right, but if I was following a script it would be going better.',
		],
		suitableKinds: ['tease', 'consistency', 'interruption'],
		personaRequires: [],
		personaResists: [],
		minStage: 2,
		maxStage: 6,
		effect: { momentum: 4, interest: 3, comfort: 1, trust: 0 },
		backfire: 'Reframing a clear refusal is pressure, not wit.',
		unlockedByDefault: true,
		unlockMastery: 0,
	},
	compact_story: {
		id: 'compact_story',
		name: 'Compact Story',
		category: 'story',
		description: 'A short personal story that shows something about you without announcing it. Three sentences, one detail, a point.',
		beats: ['relevant to the current topic', 'contains one concrete detail', 'ends with a point or a question, not a boast'],
		paraphrases: [
			'I moved here with two suitcases and a tabla nobody asked me to bring. The tabla is doing better than I am.',
			'My first week at the studio I set up drums for a band I had never heard of. Turned out to be a funeral. Nobody told me.',
		],
		suitableKinds: ['conversation', 'recovery'],
		personaRequires: [],
		personaResists: [],
		minStage: 3,
		maxStage: 6,
		effect: { momentum: 3, interest: 3, comfort: 3, trust: 2 },
		backfire: 'A story that contradicts something you said earlier triggers a congruence challenge.',
		unlockedByDefault: true,
		unlockMastery: 0,
	},
	callback: {
		id: 'callback',
		name: 'Callback',
		category: 'callback',
		description: 'Reference a specific detail she mentioned earlier in this conversation. It shows you were listening.',
		beats: ['references a detail she actually said this encounter', 'uses it to advance the topic or make a joke'],
		paraphrases: ['You said you would leave by eleven. It is eleven fifteen. This is on me.', 'Is this the restaurant with the lighting you hated?'],
		suitableKinds: ['conversation', 'recovery', 'invitation', 'logistics'],
		personaRequires: [],
		personaResists: [],
		minStage: 3,
		maxStage: 8,
		effect: { momentum: 4, interest: 3, comfort: 3, trust: 3 },
		backfire: 'Calling back a detail she never said reads as confusion or a script.',
		unlockedByDefault: true,
		unlockMastery: 0,
	},
	direct_interest: {
		id: 'direct_interest',
		name: 'Direct Interest',
		category: 'direct',
		description: 'Say plainly that you are interested, once, without demanding a response.',
		beats: ['states interest clearly and specifically', 'no pressure or ultimatum', 'leaves her room to respond'],
		paraphrases: ['I came over because I wanted to talk to you. That is the whole strategy.', 'I like you. I wanted to say it before your friends decide for you.'],
		suitableKinds: ['conversation', 'invitation', 'consistency'],
		personaRequires: [],
		personaResists: [],
		minStage: 4,
		maxStage: 8,
		effect: { momentum: 5, interest: 4, comfort: 0, trust: 3 },
		backfire: 'Delivered before any connection exists, it is an ask with nothing behind it.',
		unlockedByDefault: true,
		unlockMastery: 0,
	},
	mutual_qualification: {
		id: 'mutual_qualification',
		name: 'Mutual Qualification',
		category: 'qualification',
		description: 'Ask her something that lets her show what she is like, and answer the same question yourself.',
		beats: ['asks a question about what she values or does', 'offers your own honest answer', 'treats it as an exchange, not a test'],
		paraphrases: ['What do you do that nobody claps for? Mine is I read building codes for fun.', 'Best decision you made this year? I will go first if you want.'],
		suitableKinds: ['conversation'],
		personaRequires: [],
		personaResists: [],
		minStage: 3,
		maxStage: 6,
		effect: { momentum: 3, interest: 3, comfort: 3, trust: 3 },
		backfire: 'Asked like a job interview, it becomes an interrogation.',
		unlockedByDefault: false,
		unlockMastery: 1,
	},
	transition: {
		id: 'transition',
		name: 'Conversational Transition',
		category: 'transition',
		description: 'Move from one topic to the next using something she just said as the bridge.',
		beats: ['uses a word or idea from her last line', 'moves to a new topic without a hard reset'],
		paraphrases: ['Restaurants. Okay, worst meal you have paid money for.', 'Half marathons, so you do like suffering with a finish line.'],
		suitableKinds: ['conversation', 'recovery', 'interruption'],
		personaRequires: [],
		personaResists: [],
		minStage: 2,
		maxStage: 7,
		effect: { momentum: 3, interest: 2, comfort: 2, trust: 0 },
		backfire: 'A transition that ignores what she just said is a subject change.',
		unlockedByDefault: false,
		unlockMastery: 1,
	},
	shared_scenario: {
		id: 'shared_scenario',
		name: 'Playful Shared Scenario',
		category: 'scenario',
		description: 'Invent a small hypothetical the two of you are in together, and let her build on it.',
		beats: ['proposes a hypothetical that includes both of you', 'gives her a role or a choice in it', 'stays light'],
		paraphrases: ['If we had to rob this place, you are clearly the lookout. I am the guy who trips the alarm.', 'New rule: whoever says the word networking first buys the next round.'],
		suitableKinds: ['conversation', 'tease'],
		personaRequires: [],
		personaResists: ['dislikesSpotlight'],
		minStage: 3,
		maxStage: 6,
		effect: { momentum: 4, interest: 3, comfort: 2, trust: 0 },
		backfire: 'A scenario that puts her on stage in front of strangers backfires with someone who hates the spotlight.',
		unlockedByDefault: false,
		unlockMastery: 2,
	},
	recovery_acknowledgment: {
		id: 'recovery_acknowledgment',
		name: 'Recovery Acknowledgment',
		category: 'recovery',
		description: 'Name the awkward moment plainly, briefly, without groveling, then move on.',
		beats: ['admits the misstep in one sentence', 'no excessive apology or self-attack', 'moves forward with a question or a new thread'],
		paraphrases: ['That came out like a line. It was not meant to. What were you saying about the project?', 'Okay, that was clumsy. Let me try that again as a person.'],
		suitableKinds: ['recovery', 'consistency'],
		personaRequires: [],
		personaResists: [],
		minStage: 2,
		maxStage: 8,
		effect: { momentum: 4, interest: 1, comfort: 4, trust: 4 },
		backfire: 'Over-apologizing turns a small moment into a big one.',
		unlockedByDefault: false,
		unlockMastery: 1,
	},
	specific_invitation: {
		id: 'specific_invitation',
		name: 'Specific Invitation',
		category: 'invitation',
		description: 'Propose one concrete thing: a place, a day, a time. Make it easy to say yes or no.',
		beats: ['names a specific activity', 'names a specific time or day', 'leaves an easy out'],
		paraphrases: ['There is a jazz bar on Fourth that does a Sunday matinee. Come with me this week.', 'Give me your number and I will send you the restaurant with the good lighting. Thursday if you are free.'],
		suitableKinds: ['invitation', 'logistics'],
		personaRequires: [],
		personaResists: [],
		minStage: 6,
		maxStage: 8,
		effect: { momentum: 5, interest: 3, comfort: 2, trust: 3 },
		backfire: 'Delivered before she is interested, it is a logistics problem she did not ask for.',
		unlockedByDefault: false,
		unlockMastery: 2,
	},
	graceful_exit: {
		id: 'graceful_exit',
		name: 'Graceful Exit',
		category: 'exit',
		description: 'Leave cleanly and warmly on your own terms, without a jab or a plea.',
		beats: ['signals departure clearly', 'keeps warmth', 'no attempt to reopen or guilt'],
		paraphrases: ['I am going to let you get back to your friends. It was good talking to you.', 'This was the best part of my night. Enjoy the rest of yours.'],
		suitableKinds: ['conversation', 'rejection', 'boundary', 'logistics', 'interruption'],
		personaRequires: [],
		personaResists: [],
		minStage: 1,
		maxStage: 8,
		effect: { momentum: 0, interest: 0, comfort: 2, trust: 2 },
		backfire: 'An exit with a parting shot is not graceful.',
		unlockedByDefault: false,
		unlockMastery: 1,
	},
};

export const ROUTINE_IDS = Object.keys(ROUTINES);
export const DEFAULT_LOADOUT = ['observation_opener', 'agree_amplify', 'playful_reframe', 'compact_story', 'callback', 'direct_interest'];
export const MAX_EQUIPPED = 4;
